# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Selahattin Ünlü
tagline:             Full Time Developer && Part Time Student
url:                 http://selahattinunlu.com
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Selahattin Ünlü
  url:               https://twitter.com/selahattinunlu
  email:             selahattin.unlu@yandex.com

social_networks:
  twitter:
     url: http://twitter.com/selahattinunlu
     username: selahattinunlu



# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:       
  Hakkımda: '/hakkimda'
  Seriler: '/seriler'
  #Freelance: '/isler'
  Arşiv: '/arsiv'
  Feed: '/atom.xml'

collections:
  # Blog Serileri
  seriler:
    output: true
    permalink: seriler/:path/
  # Projeler
  projeler:
    output: true
    permalink: projeler/:path/
  # İşler
  isler:
    output: true
    permalink: isler/:path/
  # Demolar
  demo:
    output: true
    permalink: demo/:path.html

# Defaults
defaults:
  # posts
  - scope:
      path: ''
      type: post
    values:
      layout: post
      comments: 1
  # series
  - scope:
      path: ''
      type: seriler
    values:
      layout: series
      comments: 1
  # drafts
  - scope:
      path: ''
      type: draft
    values:
      layout: post
      comments: 1
  # pages
  - scope:
      path: ''
      type: page
    values:
      layout: page
      comments: 0
  # works
  - scope:
      path: ''
      type: isler
    values:
      layout: work
      comments: 1
  # projects
  - scope:
      path: ''
      type: projeler
    values:
      layout: project
      comments: 1

# ==== SOLID Series =========
solid_serie: 
  title: "SOLID Prensipleri"
  uri: '/seriler/solid-prensipleri'
  posts: 
    - title: "Nedir, Neden İhtiyaç Duyulmuştur?"
      uri: "/solid-nedir-neden-ihtiyac-duyulmustur"

    - title: 'Single Responsibility'
      uri: '/solid-single-responsibility'

    - title: 'Open - Closed Prensibi'
      uri: '/solid-open-closed'

    - title: 'Liskov Substitution Prensibi'
      uri: '/solid-liskov-substitution'

    - title: 'Interface Segregation Prensibi'
      uri: '/solid-interface-segregation'

    - title: 'Dependency Inversion Prensibi'
      uri: '/solid-dependency-inversion'

# ==== Git Series =========
git_serie:
  title: "Git"
  uri: '/seriler/git'
  posts: 
    - title: "Nedir, Neden Kullanmalıyız?"
      uri: "/git-nedir-neden-kullanmaliyiz"

    - title: "Öğrenmek İçin Kaynaklar"
      uri: "/git-ogrenmek-icin-kaynaklar"

    - title: "GUI Araçlar"
      uri: "/git-gui-araclar"

    - title: "Yanlış Commit Mesajını Düzeltme"
      uri: "/git-yanlis-commit-mesajini-duzeltme"

    - title: "Stash İle Mevcut Çalışmaya Ara Vermek"
      uri: "/git-stash-ile-mevcut-calismaya-ara-vermek"

    - title: "Remote Repo'daki Commiti Geri Alma"
      uri: "/git-remote-repo-daki-commit-i-geri-alma"

    - title: "Remote Branchları Listeleme"
      uri: "/git-remote-branch-lari-listeleme"

    - title: "Branch Silme İşlemi"
      uri: "/git-branch-silme-islemi"

    - title: "Lokal Branchı Remote Git Reposuna Göndermek"
      uri: "/git-lokal-branch-i-remote-git-reposuna-gondermek"

    - title: "Merge Conflict Nedir, Nasıl Düzeltilir?"
      uri: "/git-merge-conflict-nedir-nasil-duzeltilir"

    - title: "'git pull' ile 'git fetch' Arasındaki Fark Nedir?"
      uri: "/git-git-pull-ile-git-fetch-arasindaki-fark-nedir"

    - title: "Birden Fazla Repoya Commit Gönderme"
      uri: "/git-birden-fazla-repo-ya-commit-gonderme"

    - title: "VPS'de Otomatik Deployment"
      uri: "/git-vps-de-otomatik-deployment"

# ==== Composer Series =========
composer_serie:
  title: "Composer"
  uri: '/seriler/composer'
  posts: 
    - title: "Nedir?"
      uri: "/composer-nedir"

    - title: "Paket Geliştirmek"
      uri: "/composer-paket-gelistirmek"