# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Selahattin Ünlü
tagline:             Full Time Developer && Part Time Student
url:                 http://selahattinunlu.com
paginate:            10
paginate_path:      "blog/page:num"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Selahattin Ünlü
  url:               https://twitter.com/selahattinunlu
  email:             selahattin.unlu@yandex.com

social_networks:
  twitter:
     url: http://twitter.com/selahattinunlu
     username: selahattinunlu



# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:       
  Hakkımda: '/hakkimda'
  Seriler: '/seriler'
  Freelance: '/isler'
  Projeler: '/projeler'
  Arşiv: '/arsiv'
  Feed: '/atom.xml'

collections:
  # Etiketlere Göre İçerikler
  etiketler:
    output: true
    permalink: etiket/:path/
  # Blog Serileri
  seriler:
    output: true
    permalink: seriler/:path/
  # Demolar
  demo:
    output: true
    permalink: demo/:path.html

# Defaults
defaults:
  # posts
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: 1
  # series
  - scope:
      path: ''
      type: seriler
    values:
      layout: series
      comments: 1
  # drafts
  - scope:
      path: ''
      type: drafts
    values:
      layout: post
      comments: 1
  # pages
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: 0