# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Selahattin Ünlü
tagline:             Full Time Developer && Part Time Student
url:                 http://selahattinunlu.com
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Selahattin Ünlü
  url:               https://twitter.com/selahattinunlu
  email:             selahattin.unlu@yandex.com

social_networks:
  twitter:
     url: http://twitter.com/selahattinunlu
     username: selahattinunlu



# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:       
  Hakkımda: '/hakkimda'
  Arşiv: '/arsiv'
  Feed: '/atom.xml'

collections:
  # Belgeler
  algoritmalar:
    output: true
    permalink: belgeler/algoritmalar/:path/
  tasarim-desenleri:
    output: true
    permalink: belgeler/tasarim-desenleri/:path/
  yazilim-prensipleri:
    output:  true
    permalink: belgeler/yazilim-prensipleri/:path/
  yazilimcilar:
    output:  true
    permalink: belgeler/yazilimcilar/:path/

  # Projeler
  projeler:
    output: true
    permalink: projeler/:path/
  isler:
    output: true
    permalink: isler/:path/

# Defaults
defaults:
  # posts
  - scope:
      path: ''
      type: post
    values:
      layout: post
      comments: 1
  # pages
  - scope:
      path: ''
      type: page
    values:
      layout: page
  # documents
  - scope:
      path: ''
      types: [algoritmalar, tasarim-desenleri, yazilimcilar, yazilim-prensipleri]
    values:
      layout: document
      comments: 1
  # works
  - scope:
      path: ''
      type: isler
    values:
      layout: work
      comments: 1
  # projects
  - scope:
      path: ''
      type: projeler
    values:
      layout: project
      comments: 1